projects:
  app:
    schemaPath: apollo-server/schema.graphql
    includes:
      - '**/*.gql'
    extensions:
      endpoints:
        default: 'http://lazytrip-env.rnvmgyxxww.eu-west-3.elasticbeanstalk.com/graphql'
