projects:
  app:
    schemaPath: apollo-server/schema.graphql
    includes:
      - '**/*.gql'
    extensions:
      endpoints:
        default: 'http://ec2-35-180-43-129.eu-west-3.compute.amazonaws.com:4000/graphql'
